blank_issues_enabled: false
contact_links:
  - name: Getting Started Guide ğŸƒ
    url: https://github.com/autokey/autokey/wiki/Beginners-Guide
    about: Getting started with AutoKey.

  - name: Frequently Asked Questions ğŸ¤”
    url: https://github.com/autokey/autokey/wiki/FAQ
    about: Frequently Asked Questions about AutoKey.

  - name: Ask Your Own Question â“
    url: https://github.com/autokey/autokey/discussions
    about: Ask a question or request support for using AutoKey
    
  - name: Join Our Community ğŸ¤²ğŸ¼
    url: https://gitter.im/autokey/autokey
    about: Chat with us on Gitter.
    
